name: Deploy to EC2

on:
  push:
    branches:
      - main  # or change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Fall_Foliage_ML_Model
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fallfoliage
